"""initial migration

Revision ID: aeb5ab07a371
Revises: 
Create Date: 2026-02-17 18:40:09.009516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb5ab07a371'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('артикул', sa.String(length=20), nullable=False),
    sa.Column('назва', sa.String(length=255), nullable=False),
    sa.Column('відділ', sa.BigInteger(), nullable=False),
    sa.Column('група', sa.String(length=100), nullable=False),
    sa.Column('кількість', sa.String(length=50), nullable=False),
    sa.Column('відкладено', sa.Integer(), nullable=False),
    sa.Column('місяці_без_руху', sa.Integer(), nullable=True),
    sa.Column('сума_залишку', sa.Float(), nullable=True),
    sa.Column('ціна', sa.Float(), nullable=True),
    sa.Column('активний', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_активний'), 'products', ['активний'], unique=False)
    op.create_index(op.f('ix_products_артикул'), 'products', ['артикул'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_lists_user_id'), 'saved_lists', ['user_id'], unique=False)
    op.create_table('temp_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_lists_user_id'), 'temp_lists', ['user_id'], unique=False)
    op.create_table('saved_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('article_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['saved_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_list_items')
    op.drop_index(op.f('ix_temp_lists_user_id'), table_name='temp_lists')
    op.drop_table('temp_lists')
    op.drop_index(op.f('ix_saved_lists_user_id'), table_name='saved_lists')
    op.drop_table('saved_lists')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_артикул'), table_name='products')
    op.drop_index(op.f('ix_products_активний'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
